.PHONY: clean release docs

-include make.conf

# basic compiling and linking - rarely changed
OPTIONS = -DLINUX -DELC $(foreach FEATURE, $(FEATURES), -D$(FEATURE)) -D_7ZIP_ST

# ajout des options nécessaires selon l'architecture (spécifiée par ARCH= ou détection auto de l'OS)
SUBARCH := $(shell uname -m | sed -e s/i.86/x86/)
ARCH ?= $(SUBARCH)
ifeq ($(ARCH),x86_64)
	PLATFORM = -march=x86-64
#	PLATFORM = -march=k8
#	OPTIONS += -DX86_64
else
ifeq ($(ARCH),ppc)
	PLATFORM = -mpowerpc -malign-natural
	OPTIONS += -DEL_BIG_ENDIAN
else
ifeq ($(ARCH),ppc_64)
	PLATFORM = -mpowerpc
	OPTIONS += -DEL_BIG_ENDIAN
#	OPTIONS += -DX86_64
endif
endif
endif

# Si on veut utiliser gprof décommenter la ligne suivante
#OPTIONS += -pg

CFLAGS=$(PLATFORM) $(CWARN) -O0 -ggdb -pipe $(OPTIONS) $(shell sdl-config --cflags) $(shell xml2-config --cflags) -fno-strict-aliasing $(EXTRA_INCLUDES)
_CFLAGS=$(PLATFORM) -O2 -fomit-frame-pointer -ffast-math -pipe $(OPTIONS) $(shell sdl-config --cflags) $(shell xml2-config --cflags) -fno-strict-aliasing $(EXTRA_INCLUDES)
CXXFLAGS=$(PLATFORM) $(CXXWARN) -O0 -ggdb -pipe $(OPTIONS) $(shell sdl-config --cflags) $(shell xml2-config --cflags) -fno-strict-aliasing $(EXTRA_INCLUDES)
_CXXFLAGS=$(PLATFORM) -O3 -fomit-frame-pointer -ffast-math -pipe $(OPTIONS) $(shell sdl-config --cflags) $(shell xml2-config --cflags) -fno-strict-aliasing $(EXTRA_INCLUDES)

PNG_SCREENSHOT_LIBS = $(shell pkg-config libpng --libs)
LDFLAGS=$(shell sdl-config --libs) \
	$(shell pkg-config libxml-2.0 --libs) \
	$(shell pkg-config SDL_net --libs) \
	$(shell pkg-config SDL_image --libs) \
	$(shell pkg-config cal3d --libs) \
	$(shell pkg-config gl --libs) \
	$(shell pkg-config glu --libs) \
	$(shell pkg-config openal --libs) \
	$(shell pkg-config vorbis --libs) \
	$(shell pkg-config vorbisfile --libs) \
	$(shell pkg-config zlib --libs) \
	$(foreach FEATURE, $(FEATURES), $($(FEATURE)_LIBS)) \
	$(shell xslt-config --libs) \
	$(shell pkg-config x11 --libs) -lm -lstdc++

_LDFLAGS=$(XDIR) -lGL -lpthread -lstdc++ -lm -ldl

LIBD=../libs
STATICLIBS=$(LIBD)/libSDL_net.a $(LIBD)/libSDL.a $(LIBD)/libSDL_image.a $(LIBD)/libopenal.a $(LIBD)/libvorbisfile.a $(LIBD)/libvorbis.a $(LIBD)/libogg.a $(LIBD)/libxml2.a $(LIBD)/libcal3d.a $(LIBD)/libpng.a $(LIBD)/libasound.a $(LIBD)/libGLU.a $(LIBD)/libz.a $(EXTRA_STATICLIBS) -lX11
include objs.mk
HEADER_DIRS = . books eye_candy io pawn fsaa engine xz


DEP_FILES=$(foreach OBJ, $(COBJS), .deps/$(OBJ).P) $(foreach OBJ, $(CXXOBJS), .deps/$(OBJ).P)
#(shell echo $OBJ |sed s/\.o/\.P/))

EXE=le.$(ARCH).linux.bin

ifndef CC
CC=gcc
endif
ifndef CXX
CXX=g++
endif
ifndef LINK
LINK=gcc
endif

all: $(EXE)

# the compile targets
$(EXE): $(OBJS)
	@echo "  LINK $(EXE)"
	@$(LINK) $(CFLAGS) -o $(EXE) $(OBJS) $(LDFLAGS)

#recompile on Makefile or conf change
#.depend $(OBJS): Makefile.linux make.conf

DEPS_MAGIC := $(shell mkdir .deps .deps/io .deps/shader .deps/eye_candy .deps/exceptions .deps/xz .deps/xml .deps/fsaa .deps/engine > /dev/null 2>&1 || :)

$(COBJS): %.o: %.c Makefile.linux make.conf
	@echo "  CC   $@"
	@if $(CC) $(CFLAGS) -MT '$@' -MD -MP -MF '.deps/$@.pp' -c $< -o $@; then \
		mv ".deps/$@.pp" ".deps/$@.P"; \
	else rm -f ".deps/$@.pp"; exit 1; \
	fi

$(CXXOBJS): %.o: %.cpp Makefile.linux make.conf
	@echo "  CXX  $@"
	@if $(CXX) $(CXXFLAGS) -MT '$@' -MD -MP -MF '.deps/$@.pp' -c $< -o $@; then \
		mv ".deps/$@.pp" ".deps/$@.P"; \
	else rm -f ".deps/$@.pp"; exit 1; \
	fi

release:
	@$(MAKE) -f Makefile.linux 'CFLAGS=$(_CFLAGS)' 'CXXFLAGS=$(_CXXFLAGS)'

static:
	@$(MAKE) -f Makefile.linux 'CFLAGS=$(_CFLAGS)' 'CXXFLAGS=$(_CXXFLAGS)' 'LDFLAGS=$(_LDFLAGS) -lGL' 'OBJS=$(OBJS) $(STATICLIBS)' 'EXE=le.$(ARCH).static.linux.bin'

clean:
	rm -f $(OBJS) $(EXE)
	rm -rf .deps

docs:
	cd docs && doxygen Doxyfile

.depend: $(foreach HEADER_DIR, $(HEADER_DIRS), $(wildcard $(HEADER_DIR)/*.h))
	$(CC) $(CFLAGS) -MM $(patsubst %.o, %.c, $(COBJS)) >.depend
	$(CXX) $(CXXFLAGS) -MM $(patsubst %.o, %.cpp, $(CXXOBJS)) >>.depend

make.conf: make.defaults
	@if (test -f $@ -a '$(UPDATE_CONF)' != 'yes'); \
	then \
		echo '**'; \
		echo '* WARNING: $< is newer than $@!'; \
		echo '* Proceeding in 10 seconds, hit Ctrl-C to abort...'; \
		echo '*'; \
		sleep 10; \
	else \
		cp $< $@; \
	fi


pawn_scripts/features.inc: make.conf
	echo "#if defined _features_included" > $@; \
	echo "\t#endinput" >> $@; \
	echo "#endif" >> $@; \
	echo "#define _features_included" >> $@; \
	for feature in $(FEATURES); do \
		echo "#define $$feature" >> $@; \
	done

-include $(DEP_FILES)
