.PHONY: clean docs
-include make.defaults make.conf
all :
ARCH :=
STATIC ?= 0
BUILD ?= release
LIBDIR ?= ../libs
builds := release debug
build := $(strip $(foreach b,${builds},$(if $(findstring ${BUILD},$b),$b)))
$(if ${build},,$(error Invalid build type "${BUILD}", expecting one of: ${builds}))
$(if $(shell [ $(words ${build}) -gt 1 ] && echo 1),$(error "${BUILD}" is ambiguous, expecting one of: ${builds}))
$(if $(shell [ "${STATIC}" = 0 -o "${STATIC}" = 1 ] && echo 1),,$(error Expecting 0 or 1 for STATIC, not "${STATIC}"))
arch := $(if ${ARCH},${ARCH},$(shell uname -m))
static0 := shared
static1 := static
linkage := ${static${STATIC}}
tag := linux.${arch}.${linkage}.${build}
exe := le.${tag}.bin
bdir := build.${tag}
include objs.mk
objs = ${OBJS}
cal3d_dir := cal3d_12/src
cal3d_srcs := $(filter-out %/calxmlbindings.cpp,$(wildcard ${cal3d_dir}/cal3d/*.cpp))
cal3d_cppflags := -I${cal3d_dir}
objs += ${cal3d_srcs:.cpp=.o}
-include ${objs:%.o=${bdir}/%.d}
compiler := gcc
cc.gcc := gcc
cxx.gcc := g++
ld.gcc := g++
cc := ${cc.${compiler}}
cxx := ${cxx.${compiler}}
ld := ${ld.${compiler}}
flags.x86_64 := -march=x86-64 -mtune=generic
flags.i686 := -march=i686
flags.ppc := -mpowerpc -malign-natural
cppflags.ppc += -DEL_BIG_ENDIAN
flags.ppc64 := -mpowerpc
cppflags.ppc64 := -DEL_BIG_ENDIAN
flags.gcc := -Wall -Werror -Wfatal-errors ${flags.${arch}} -pipe -fexceptions -fno-omit-frame-pointer -ffast-math
flags := ${flags.${compiler}} ${FLAGS}
cpp_file_name0 = -D__FILE_NAME__=\"$(notdir $<)\"
cpp_has_file_name := $(shell [ $(firstword $(subst ., ,$(shell ${cc} -dumpversion))) -ge 12 ] && echo 1 || echo 0)
ver_git := $(shell git describe --always --tag)
cppflags.static := -DLIBXML_STATIC -DAL_LIBTYPE_STATIC
cppflags = ${cppflags.${arch}} -DLINUX -DELC -D_7ZIP_ST ${cppflags.${linkage}} -DVER_GIT=\"${ver_git}\" $(foreach f,${FEATURES}, -D$f) ${cal3d_cppflags} ${cpp_file_name${cpp_has_file_name}} ${EXTRA_INCLUDES} ${CPPFLAGS}
pkgs_static := SDL_net SDL_image glu libjpeg libpng libxml-2.0 openal sdl vorbis vorbisfile zlib
pkgs_shared := gl x11
pkgs := ${pkgs_static} ${pkgs_shared}
pkgs_cflags.shared := $(foreach p,${pkgs}, $(shell pkgconf $p --cflags))
pkgs_cflags.static := $(foreach p,${pkgs_static}, $(shell PKG_CONFIG_PATH=${LIBDIR}/pkgconfig pkgconf $p --cflags)) $(foreach p,${pkgs_shared}, $(shell pkgconf $p --cflags))
pkgs_cflags := ${pkgs_cflags.${linkage}}
cflags.gcc.release := -O2 -g ${flags}
cflags.gcc.debug := -O0 -ggdb3 ${flags}
cflags.gcc := ${cflags.gcc.${build}} ${pkgs_cflags}
cflags := ${cflags.${compiler}} ${CFLAGS}
cxxflags.gcc.release := -O2 -g ${flags}
cxxflags.gcc.debug := -O0 -ggdb3 ${flags}
cxxflags.gcc := ${cxxflags.gcc.${build}} ${pkgs_cflags} ${CXXFLAGS}
cxxflags := ${cxxflags.${compiler}} ${CXXFLAGS}
ldflags.static := -static-libgcc -static-libstdc++
ldflags := ${ldflags.${linkage}} -Wl,-Map=${bdir}/link.map ${LDFLAGS}
libnames := GLU SDL_net SDL_image SDL openal vorbisfile vorbis ogg asound xml2 jpeg png ts lzma z
libs.shared := $(foreach p,${pkgs}, $(shell pkgconf $p --libs)) $(foreach f,${FEATURES}, ${${f}_LIBS}) -lm -lstdc++
libs.static := ${libnames:%=${LIBDIR}/lib%.a} ${XDIR} -lGL -lpthread -lm -ldl -lX11 ${EXTRA_STATICLIBS}
libs := ${libs.${linkage}} ${LIBS}
compile.cxx = ${cxx} ${cxxflags} ${cppflags} -MD -MP -c $< -o $@
compile.c = ${cc} ${cflags} ${cppflags} -MD -MP -c $< -o $@
link = ${ld} ${ldflags} $^ ${libs} -o $@
bdirs : ; @mkdir -p $(addprefix ${bdir}/,$(sort $(foreach o,${objs}, $(dir $o))))
all : bdirs ${exe}
clean : ; rm -rf ${bdir} ${exe}
docs : ; cd docs && doxygen Doxyfile
.SECONDEXPANSION:
${exe} : $$(addprefix ${bdir}/,$${objs}) ; $(strip ${link})
${bdir}/%.o : %.c ; $(strip ${compile.c})
${bdir}/%.o : %.cpp ; $(strip ${compile.cxx})
