.PHONY: clean release docs all

# IMPORTANT: Dev-C++ doesn't seem to get this right, so you have to copy
# make.defaults to make.conf manually if you don't have the latter

-include make.conf

# basic compiling and linking - rarely changed
OPTIONS = -DWINDOWS -DELC -DWINVER=0x500 -mwindows $(foreach FEATURE, $(FEATURES), -D$(FEATURE))
CFLAGS=$(PLATFORM) $(CWARN) -O0 -ggdb -pipe $(OPTIONS) -fno-strict-aliasing $(EXTRA_INCLUDES)
_CFLAGS=$(PLATFORM) -O2 -fomit-frame-pointer -ffast-math -pipe -fno-strict-aliasing $(EXTRA_INCLUDES)
CXXFLAGS=$(PLATFORM) $(CXXWARN) -O0 -ggdb -pipe $(OPTIONS) -fno-strict-aliasing $(EXTRA_INCLUDES)
_CXXFLAGS=$(PLATFORM) -O3 -fomit-frame-pointer -ffast-math -pipe -fno-strict-aliasing $(EXTRA_INCLUDES)

# WARNING: the order is important! If -lX uses -lY, then you must list -lX before -lY (sic!)
LDFLAGS= $(EXTRA_LIBS) $(foreach FEATURE, $(FEATURES), $($(FEATURE)_LIBS)) \
	-llibxml2 -lSDL_net -lSDL_image -lsdl -lopenal32 -lglu32 -lopengl32 -liconv -lcal3d -lm -lstdc++ \
	-lz -lpng -lvorbisfile -lvorbis -logg
_LDFLAGS=-lopengl32 -lz
STATICLIBS=libs/libSDL_net.a libs/libSDL.a libs/libSDL_image.a libs/libopenal.a libs/libvorbisfile.a libs/libvorbis.a libs/libogg.a libs/libxml2.a libs/libcal3d.a libs/libpng.a libs/libasound.a $(EXTRA_STATICLIBS)
include objs.mk
HEADER_DIRS = . books eye_candy io pawn fsaa

EXE=el.exe

ifndef CC
CC=gcc.exe
endif
ifndef CXX
CXX=g++.exe
endif
ifndef LINK
LINK=gcc.exe
endif

TMP_LIB = libelc.a

# the compile targets
all: $(EXE);

# work around command line length restriction
$(TMP_LIB): $(OBJS)
	rm -f $@
	ar q $@ $(filter 2%, $(OBJS))
	ar q $@ $(filter 3%, $(OBJS))
	ar q $@ $(filter a%, $(OBJS))
	ar q $@ $(filter b%, $(OBJS))
	ar q $@ $(filter c%, $(OBJS))
	ar q $@ $(filter d%, $(OBJS))
	ar q $@ $(filter e%, $(OBJS))
	ar q $@ $(filter f%, $(OBJS))
	ar q $@ $(filter g%, $(OBJS))
	ar q $@ $(filter h%, $(OBJS))
	ar q $@ $(filter i%, $(OBJS))
	ar q $@ $(filter j%, $(OBJS))
	ar q $@ $(filter k%, $(OBJS))
	ar q $@ $(filter l%, $(OBJS))
	ar q $@ $(filter-out main.o, $(filter m%, $(OBJS)))
	ar q $@ $(filter n%, $(OBJS))
	ar q $@ $(filter o%, $(OBJS))
	ar q $@ $(filter p%, $(OBJS))
	ar q $@ $(filter q%, $(OBJS))
	ar q $@ $(filter r%, $(OBJS))
	ar q $@ $(filter s%, $(OBJS))
	ar q $@ $(filter t%, $(OBJS))
	ar q $@ $(filter u%, $(OBJS))
	ar q $@ $(filter v%, $(OBJS))
	ar q $@ $(filter w%, $(OBJS))
	ar q $@ $(filter x%, $(OBJS))
	ar q $@ $(filter y%, $(OBJS))
	ar q $@ $(filter z%, $(OBJS))
	ranlib $@

$(EXE): main.o $(TMP_LIB)
	windres elc_private.rc elc_private.o
	$(LINK) $(CFLAGS) $< -L. -lelc $(LDFLAGS) elc_private.o -o $(EXE)
	strip -s $(EXE)

#recompile on Makefile or conf change
.depend $(OBJS): Makefile.win make.conf

$(COBJS): %.o : %.c
	$(CC) $(CFLAGS) -c -o $@ $<

$(CXXOBJS): %.o : %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

release:
	$(MAKE) -f Makefile.win 'CFLAGS=$(_CFLAGS)' 'CXXFLAGS=$(_CXXFLAGS)'

static:
	$(MAKE) -f Makefile.win 'CFLAGS=$(_CFLAGS)' 'CXXFLAGS=$(_CXXFLAGS)' 'LDFLAGS=$(_LDFLAGS)' 'OBJS=$(OBJS) $(STATICLIBS) -lstdc++ -lGL -lGLU'

clean:
	rm -f $(OBJS) $(EXE) .depend

docs:
	cd docs && doxygen Doxyfile

.depend: $(foreach HEADER_DIR, $(HEADER_DIRS), $(wildcard $(HEADER_DIR)/*.h))
	$(CC) $(CFLAGS) -MM $(patsubst %.o, %.c, $(COBJS)) >.depend
	$(CXX) $(CXXFLAGS) -MM $(patsubst %.o, %.cpp, $(CXXOBJS)) >>.depend

make.conf: make.defaults
	@if (test -f $@ -a '$(UPDATE_CONF)' != 'yes'); \
	then \
		echo '**'; \
		echo '* WARNING: $< is newer than $@!'; \
		echo '* Proceeding in 10 seconds, hit Ctrl-C to abort...'; \
		echo '*'; \
		sleep 10; \
	else \
		cp $< $@; \
	fi

pawn_scripts/features.inc: make.conf
	echo "#if defined _features_included" > $@; \
	echo "\t#endinput" >> $@; \
	echo "#endif" >> $@; \
	echo "#define _features_included" >> $@; \
	for feature in $(FEATURES); do \
		echo "#define $$feature" >> $@; \
	done

-include .depend
